[package]
name = "quick_es_runtime"
version = "0.1.0"
authors = ["Andries Hiemstra"]
edition = "2018"
description = "An API and Utils around the QuickJS script engine"
homepage = "https://github.com/DRFos/quick_es_runtime"
keywords = ["quickjs", "javascript", "runtime", "engine"]
repository = "https://github.com/DRFos/quick_es_runtime"
license = "GPL-3.0"
documentation = "https://drfos.github.io/quick_es_runtime/quick_es_runtime/index.html"
readme = "README.md"
categories = ["development-tools"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#quick-js = "0.3.3"
#libquickjs-sys = {path = "../quickjs-rs/libquickjs-sys"}
libquickjs-sys = {git="https://github.com/theduke/quickjs-rs#6979b780"}
# quick-js = {path = "../quickjs-rs"}
lazy_static = "1.4.0"
hirofa_utils = {git="https://github.com/DRFos/utils"}
log = "0.4.11"
simple-logging = "2.0.2"
thread-id = "3.3.0"
num_cpus = "1.13.0"
uuid = {version = "0.8.1", features =["v4"]}
rayon = "1.3.1"
lru = "0.6.0"
either = "1.6.0"

[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false # Disable features which are enabled by default
features = []
#features = ["precommit-hook", "run-cargo-test", "run-cargo-clippy"]