[package]
name = "quickjs_runtime"
version = "0.8.1"
authors = ["Andries Hiemstra <info@hirofa.com>"]
edition = "2018"
description = "Wrapper API and utils for the QuickJS JavaScript engine with support for Promise, Module, Async/await"
homepage = "https://github.com/HiRoFa/quickjs_es_runtime"
keywords = ["quickjs", "javascript", "runtime", "async", "engine"]
repository = "https://github.com/HiRoFa/quickjs_es_runtime"
license = "MIT"
documentation = "https://hirofa.github.io/quickjs_es_runtime/quickjs_runtime/index.html"
readme = "README.md"
categories = ["development-tools"]

[features]
default = ["console", "setimmediate", "setinterval", "settimeout"]
tokio_full = ["tokio/full"]
console = []
settimeout = []
setinterval = []
setimmediate = []


[dependencies]
hirofa_utils = "0.5.2"
#hirofa_utils = {path="../utils"}
#hirofa_utils = {git="https://github.com/HiRoFa/utils"}
backtrace = "0.3.56"
libquickjs-sys = "0.10.0"
lazy_static = "1.4.0"
log = "0.4"
simple-logging = "2.0"
num_cpus = "1.13"
rand = "0.7"
thread-id = "3.3"
futures = "0.3"
tokio = {version = "1.4", features = ["rt-multi-thread", "rt", "bytes", "fs", "io-std", "io-util", "libc", "macros", "memchr", "winapi", "tracing", "time", "tokio-macros", "test-util", "sync", "parking_lot", "once_cell", "mio", "net", "num_cpus"]}
serde_json = "1.0"
serde = {version="1.0", features=["derive"]}

[dev-dependencies]
#green_copper_runtime =  { git = 'https://github.com/HiRoFa/GreenCopperRuntime', branch="main", features = ["console"]}

[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false # Disable features which are enabled by default
# features = ["precommit-hook", "run-cargo-test", "run-cargo-clippy"]
