[package]
name = "quickjs_runtime"
version = "0.3.0"
authors = ["Andries Hiemstra <info@hirofa.com>"]
edition = "2018"
description = "An API and Utils around the QuickJS script engine"
homepage = "https://github.com/HiRoFa/quickjs_es_runtime"
keywords = ["quickjs", "javascript", "runtime", "engine", "js"]
repository = "https://github.com/HiRoFa/quickjs_es_runtime"
license = "GPL-3.0"
documentation = "https://hirofa.github.io/quickjs_es_runtime/quickjs_runtime/index.html"
readme = "README.md"
categories = ["development-tools"]

[dependencies]

libquickjs-sys = "0.9.0"
lazy_static = "1.4.0"
log = "0.4.11"
simple-logging = "2.0.2"
num_cpus = "1.13.0"
rand = "0.7.3"
thread-id = "3.3.0"
uuid = {version = "0.8.1", features =["v4"]}
rayon = "1.3.1"
futures = "0.3"

tokio = {version = "1.4.0", features = ["full"]}

[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false # Disable features which are enabled by default
#features = ["precommit-hook", "run-cargo-test", "run-cargo-clippy"]
