[package]
name = "quickjs_runtime"
version = "0.4.1"
authors = ["Andries Hiemstra <info@hirofa.com>"]
edition = "2018"
description = "Wrapper API and utils for the QuickJS JavaScript engine"
homepage = "https://github.com/HiRoFa/quickjs_es_runtime"
keywords = ["quickjs", "javascript", "runtime", "engine", "js"]
repository = "https://github.com/HiRoFa/quickjs_es_runtime"
license = "MIT"
documentation = "https://hirofa.github.io/quickjs_es_runtime/quickjs_runtime/index.html"
readme = "README.md"
categories = ["development-tools"]

[features]
tokio_full = ["tokio/full"]

[dependencies]
hirofa_utils = "0.1"
backtrace = "0.3.56"
libquickjs-sys = "0.9.0"
lazy_static = "1.4.0"
log = "0.4.11"
simple-logging = "2.0.2"
num_cpus = "1.13.0"
rand = "0.7.3"
thread-id = "3.3.0"
futures = "0.3"
tokio = {version = "1.4", features = ["rt-multi-thread", "rt", "bytes", "fs", "io-std", "io-util", "libc", "macros", "memchr", "winapi", "tracing", "time", "tokio-macros", "test-util", "sync", "parking_lot", "once_cell", "mio", "net", "num_cpus"]}

[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false # Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-test", "run-cargo-clippy"]
